# Generated by Django 5.2 on 2025-05-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="employer_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Employer Name"
            ),
        ),
    ]
