# Generated by Django 5.2 on 2025-05-20 01:04

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_profile_employer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date(1900, 1, 1), verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+2347084123456",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
